import type { ThreatEvent } from "./types";

const now = Date.now();
const minutesAgo = (minutes: number) =>
  new Date(now - minutes * 60_000).toISOString();

export const initialEvents: ThreatEvent[] = [
  {
    id: "CG-2048",
    timestamp: minutesAgo(2),
    source: "Email gateway",
    subject: "Payroll document requires immediate review",
    category: "Credential phishing",
    severity: "Critical",
    score: 96,
    status: "Investigating",
    summary: "A payroll-themed message combines urgent language with an external sign-in link.",
    indicators: ["Urgent account action requested", "Credential collection language", "Untrusted shortened URL"],
    recommendations: ["Quarantine message", "Block the destination URL", "Notify the addressed user"],
  },
  {
    id: "CG-2047",
    timestamp: minutesAgo(8),
    source: "Identity monitor",
    subject: "Repeated sign-in failures from a new device",
    category: "Account takeover",
    severity: "High",
    score: 88,
    status: "Contained",
    summary: "A burst of failed authentication attempts came from an unfamiliar device and location.",
    indicators: ["12 failed attempts in 4 minutes", "Device not seen for this account", "Location differs from usual sign-ins"],
    recommendations: ["Revoke active sessions", "Require MFA re-authentication", "Temporarily rate-limit the source"],
  },
  {
    id: "CG-2046",
    timestamp: minutesAgo(16),
    source: "User report",
    subject: "Voice note claims to be from the finance director",
    category: "Impersonation / deepfake concern",
    severity: "High",
    score: 81,
    status: "Investigating",
    summary: "An unverified voice message requests an urgent transfer using a new payment account.",
    indicators: ["Authority impersonation claim", "Urgent financial request", "Unverified voice and payment details"],
    recommendations: ["Verify through a known callback number", "Pause payment", "Escalate for human media review"],
  },
  {
    id: "CG-2045",
    timestamp: minutesAgo(29),
    source: "Web proxy",
    subject: "Look-alike identity portal domain observed",
    category: "Malicious URL",
    severity: "Medium",
    score: 67,
    status: "New",
    summary: "The domain uses a brand-like spelling and redirects toward a sign-in page.",
    indicators: ["Look-alike brand spelling", "Sign-in page path", "Redirect target not verified"],
    recommendations: ["Block URL at the web gateway", "Check proxy logs for visits", "Warn users who opened the page"],
  },
  {
    id: "CG-2044",
    timestamp: minutesAgo(44),
    source: "API monitor",
    subject: "Unusual burst of requests to the account endpoint",
    category: "API abuse",
    severity: "Medium",
    score: 59,
    status: "Resolved",
    summary: "Request volume briefly exceeded the configured baseline for one client token.",
    indicators: ["Request burst above baseline", "Repeated access to one endpoint"],
    recommendations: ["Review client-token ownership", "Keep rate limits enabled"],
  },
  {
    id: "CG-2043",
    timestamp: minutesAgo(71),
    source: "Endpoint telemetry",
    subject: "PowerShell launched with an encoded argument",
    category: "Suspicious execution",
    severity: "Low",
    score: 38,
    status: "Resolved",
    summary: "An encoded command was observed; the telemetry alone does not establish malicious intent.",
    indicators: ["Encoded process argument", "Parent process requires review"],
    recommendations: ["Review the process tree", "Confirm the activity with the device owner"],
  },
];

export const activity = [
  { time: "14:42", label: "Payroll-themed message flagged", kind: "danger" },
  { time: "14:36", label: "Unusual login burst contained", kind: "warning" },
  { time: "14:28", label: "Voice impersonation reported", kind: "warning" },
  { time: "14:15", label: "Look-alike URL added to review", kind: "info" },
  { time: "13:58", label: "API rate limit triggered", kind: "info" },
];
